apiVersion: v1
kind: Secret
metadata:
  name: synergyswift-secrets
type: Opaque
stringData:
  db-host: "<DB_HOST>"
  db-username: "<DB_USERNAME>"
  db-password: "<DB_PASSWORD>"
  redis-host: "<REDIS_HOST>"
  redis-password: "<REDIS_PASSWORD>"
  jwt-secret: "<JWT_SECRET>"
  smtp-password: "<SMTP_PASSWORD>"
  whatsapp-token: "<WHATSAPP_ACCESS_TOKEN>"
